"""empty message

Revision ID: 709c473acd15
Revises: 
Create Date: 2018-03-08 22:26:32.449550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709c473acd15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gamers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamers_email'), 'gamers', ['email'], unique=True)
    op.create_index(op.f('ix_gamers_first_name'), 'gamers', ['first_name'], unique=False)
    op.create_index(op.f('ix_gamers_last_name'), 'gamers', ['last_name'], unique=False)
    op.create_index(op.f('ix_gamers_username'), 'gamers', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('library',
    sa.Column('games_id', sa.Integer(), nullable=False),
    sa.Column('gamers_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gamers_id'], ['gamers.id'], ),
    sa.ForeignKeyConstraint(['games_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('games_id', 'gamers_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library')
    op.drop_table('games')
    op.drop_index(op.f('ix_gamers_username'), table_name='gamers')
    op.drop_index(op.f('ix_gamers_last_name'), table_name='gamers')
    op.drop_index(op.f('ix_gamers_first_name'), table_name='gamers')
    op.drop_index(op.f('ix_gamers_email'), table_name='gamers')
    op.drop_table('gamers')
    # ### end Alembic commands ###
